[book]
title = "OSNOVA AI"
authors = ["OSNOVA AI"]
language = "ru"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/necrasov-ilya/osnova-ai"
